name: ğŸš€ Deploy HTML GCP Bucket

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch para deploy"
        required: true
        default: "main"

env:
  TERRAFORM_VERSION: 1.7.5
  WORKING_DIR: infra

jobs:

  auth:
    name: ğŸ” AutenticaÃ§Ã£o GCP
    runs-on: ubuntu-latest
    steps:
      - name: Autenticar com a GCP
        id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

  terraform:
    name: âš™ï¸ Terraform Apply
    runs-on: ubuntu-latest
    needs: auth
    steps:
      - name: Checkout cÃ³digo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Autenticar com a GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Inicializar Terraform
        run: terraform init
        working-directory: ${{ env.WORKING_DIR }}

      - name: Aplicar infraestrutura
        run: terraform apply -auto-approve
        working-directory: ${{ env.WORKING_DIR }}

  deploy:
    name: ğŸ“ Copiar HTML para o Bucket
    runs-on: ubuntu-latest
    needs: terraform
    steps:
      - name: Checkout cÃ³digo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Autenticar com a GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Obter nome do bucket
        id: get_bucket
        run: |
          cd $WORKING_DIR
          BUCKET_NAME=$(terraform output -raw html_bucket_name | tr -d '\r')
          echo "bucket_name=$BUCKET_NAME" >> $GITHUB_ENV
          echo "bucket_name=$BUCKET_NAME" >> $GITHUB_OUTPUT

      - name: Copiar arquivo index.html
        run: |
          echo "ğŸ“ Copiando index.html para o bucket ${{ env.bucket_name }}..."
          gsutil cp calculadora/index.html gs://${{ env.bucket_name }}/index.html
          echo "âœ… HTML copiado com sucesso!"
